package U5T7_SMandV;

import java.util.Random;

public class Nums {
    private int int1;
    private int int2;
    private int randomNumsGenerated;
    private static int totalRandomNumsGenerated = 0;
    private Random random;

    // Constructor with precondition: int1 < int2
    public Nums(int int1, int int2) {
        if (int1 >= int2) {
            throw new IllegalArgumentException("int1 must be less than int2");
        }
        this.int1 = int1;
        this.int2 = int2;
        this.randomNumsGenerated = 0;
        this.random = new Random();
    }

    // Method to generate a random number between int1 and int2 (inclusive)
    public int randBetween() {
        int randomNumber = random.nextInt(int2 - int1 + 1) + int1;
        randomNumsGenerated++;
        totalRandomNumsGenerated++;
        return randomNumber;
    }

    // Instance method to get the number of random numbers generated by this object
    public int getRandomNumsGenerated() {
        return randomNumsGenerated;
    }

    // Static method to get the total number of random numbers generated by all Nums objects
    public static int getTotalRandomNumsGenerated() {
        return totalRandomNumsGenerated;
    }

    public static void main(String[] args) {
        System.out.println("--- 3 random numbers between 1 and 10 ---");
        Nums myNum1 = new Nums(1, 10);
        for (int i = 0; i < 3; i++) {
            System.out.println(myNum1.randBetween());
        }
        System.out.println("Random numbers generated by myNum1: " + myNum1.getRandomNumsGenerated());
        System.out.println("Total random numbers generated by all Nums objects: " + Nums.getTotalRandomNumsGenerated());

        System.out.println("\n--- 6 random numbers between 50 and 100 ---");
        Nums myNum2 = new Nums(50, 100);
        for (int i = 0; i < 6; i++) {
            System.out.println(myNum2.randBetween());
        }
        System.out.println("Random numbers generated by myNum2: " + myNum2.getRandomNumsGenerated());
        System.out.println("Total random numbers generated by all Nums objects: " + Nums.getTotalRandomNumsGenerated());

        System.out.println("\n--- 8 random numbers between 1000 and 2000 ---");
        Nums myNum3 = new Nums(1000, 2000);
        for (int i = 0; i < 8; i++) {
            System.out.println(myNum3.randBetween());
        }
        System.out.println("Random numbers generated by myNum3: " + myNum3.getRandomNumsGenerated());
        System.out.println("Total random numbers generated by all Nums objects: " + Nums.getTotalRandomNumsGenerated());
    }
}
